version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asientos
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    networks:
      - app-network
  data-generator:
    image: python:3.9
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=asientos
    volumes:
      - ./data-generator:/generator
    command: >
      sh -c '
        apt-get update &&
        apt-get install -y postgresql-client &&
        rm -rf /var/lib/apt/lists/* &&
        pip install psycopg2-binary numpy &&
        sleep 10
        python /generator/insertar_asientos.py
      '
  app:
    image: php:apache
    depends_on:
      - data-generator
    volumes:
      - ./app:/var/www/html
    command: >
        bash -c '
        apt-get update &&
        apt-get install -y unzip libpq-dev postgresql-client &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        docker-php-ext-install pdo pdo_pgsql pgsql &&
        a2enmod rewrite &&
        service apache2 restart &&
        tail -f /dev/null
        '
    networks:
      - app-network
  nginx:
    image: nginx:stable
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8989:80"
    networks:
      - app-network

networks:
  app-network:
volumes:
  dbdata:
