version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asientos
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    networks:
      - app-network
  data-generator:
    image: python:3.9
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=asientos
    volumes:
      - ./data-generator:/generator
    command: >
      sh -c '
        apt-get update &&
        apt-get install -y postgresql-client &&
        rm -rf /var/lib/apt/lists/* &&
        pip install psycopg2-binary &&
        python /generator/insertar_asientos.py
      '
  app:
    image: php:apache
    depends_on:
      - data-generator
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network
  open-browser:
    image: alpine
    depends_on:
      - app
    networks:
      - app-network
    command: >
      sh -c '
        if [[ "$(uname -s)" == "Linux" ]]; then
          xdg-open http://localhost:80
        elif [[ "$(uname -s)" == "Darwin" ]]; then
          open http://localhost:80
        elif [[ "$(uname -s)" == "MINGW"* ]]; then
          start http://localhost:89
        fi
      '
networks:
  app-network:
volumes:
  dbdata:
